[package]
name = "eris"
version = "1.3.0"
authors = ["devs <devs@erisprotocol.com>"]
edition = "2018"
description = "Liquid staking protocol for the cosmos"
license = "GPL-3.0-or-later"
homepage = "https://www.erisprotocol.com"
repository = "https://github.com/erisprotocol/liquid-staking-contracts"

[dependencies]
cosmwasm-std = { version = "1.1", features = ["stargate"] }
cw20 = "0.13.2"
cw20-base = { version = "0.13.2", features = ["library"] }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
astroport = { git = "https://github.com/astroport-fi/astroport-core.git", default-features = false, rev = "bc68bb65cc2f7d5916c1f0ea41de3b19b5b63b62" }
cosmwasm-schema = "1.0.0"
